### ISSUE TITLE
Missing library in swift

### ISSUE THREAD

**Issue by limfinity** [xcom-ag/keshlib-ios-demo#1]
To make the framework build in my swift project I had to add the `libicucore.dylib` to 'Build Phases'.

**Comment by terry-dye** [comment]
The libicucore.dylib is needed for Socket Rocket (https://github.com/square/SocketRocket). Socket Rocket is the WebSocket implementation for socket.io. The documentation should reflect this dependency.

**Comment by terry-dye** [comment]
Updated README.md file. Can be closed now.
